"""Initial Phase 01 schema

Revision ID: 7061e6706eb2
Revises: 
Create Date: 2026-09-05 12:34:15.828974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7061e6706eb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('SUPER_ADMIN','ADMIN','SECURITY_ANALYST','OPERATOR','AUDITOR')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_organization_id', 'users', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_organization_id', 'audit_logs', ['organization_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('initiated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('external_reference', sa.Text(), nullable=True),
    sa.Column('caller_identifier', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_type IN ('UPLOAD','MICROPHONE','STREAM','SIMULATED')", name='ck_calls_source_type'),
    sa.CheckConstraint("status IN ('PENDING','PROCESSING','COMPLETED','FAILED','CANCELLED')", name='ck_calls_status'),
    sa.CheckConstraint('duration_ms IS NULL OR duration_ms >= 0', name='ck_calls_duration_ms_non_negative'),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calls_created_at', 'calls', ['created_at'], unique=False)
    op.create_index('ix_calls_initiated_by_user_id', 'calls', ['initiated_by_user_id'], unique=False)
    op.create_index('ix_calls_organization_id', 'calls', ['organization_id'], unique=False)
    op.create_index('ix_calls_status', 'calls', ['status'], unique=False)
    op.create_table('audio_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('start_offset_ms', sa.BigInteger(), nullable=False),
    sa.Column('end_offset_ms', sa.BigInteger(), nullable=False),
    sa.Column('duration_ms', sa.BigInteger(), nullable=False),
    sa.Column('speech_detected', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("processing_status IN ('PENDING','PROCESSING','COMPLETED','FAILED','SKIPPED')", name='ck_audio_segments_processing_status'),
    sa.CheckConstraint('duration_ms >= 0', name='ck_audio_segments_duration_non_negative'),
    sa.CheckConstraint('end_offset_ms >= 0', name='ck_audio_segments_end_offset_non_negative'),
    sa.CheckConstraint('sequence_number >= 0', name='ck_audio_segments_sequence_number_non_negative'),
    sa.CheckConstraint('start_offset_ms >= 0', name='ck_audio_segments_start_offset_non_negative'),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'sequence_number', name='uq_audio_segments_call_seq')
    )
    op.create_index('ix_audio_segments_call_id', 'audio_segments', ['call_id'], unique=False)
    op.create_index('ix_audio_segments_call_id_sequence', 'audio_segments', ['call_id', 'sequence_number'], unique=False)
    op.create_table('voice_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('audio_segment_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=True),
    sa.Column('detection_status', sa.Text(), nullable=False),
    sa.Column('synthetic_score', sa.Numeric(), nullable=True),
    sa.Column('synthetic_probability', sa.Numeric(), nullable=True),
    sa.Column('authentic_probability', sa.Numeric(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('processing_time_ms', sa.BigInteger(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("detection_status IN ('PENDING','PROCESSING','COMPLETED','FAILED','LOW_CONFIDENCE','UNSUPPORTED')", name='ck_voice_analyses_detection_status'),
    sa.CheckConstraint('processing_time_ms IS NULL OR processing_time_ms >= 0', name='ck_voice_analyses_processing_time_non_negative'),
    sa.ForeignKeyConstraint(['audio_segment_id'], ['audio_segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_voice_analyses_audio_segment_id', 'voice_analyses', ['audio_segment_id'], unique=False)
    op.create_index('ix_voice_analyses_call_id', 'voice_analyses', ['call_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('voice_analysis_id', sa.UUID(), nullable=True),
    sa.Column('risk_score', sa.Numeric(), nullable=False),
    sa.Column('risk_level', sa.Text(), nullable=False),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_version', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("risk_level IN ('SAFE','LOW','MEDIUM','HIGH','CRITICAL')", name='ck_risk_scores_risk_level'),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name='ck_risk_scores_score_range'),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_analysis_id'], ['voice_analyses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_scores_call_id', 'risk_scores', ['call_id'], unique=False)
    op.create_index('ix_risk_scores_risk_level', 'risk_scores', ['risk_level'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('risk_score_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('LOW','MEDIUM','HIGH','CRITICAL')", name='ck_alerts_severity'),
    sa.CheckConstraint("status IN ('OPEN','ACKNOWLEDGED','INVESTIGATING','RESOLVED','DISMISSED')", name='ck_alerts_status'),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_organization_id', 'alerts', ['organization_id'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_table('alert_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('performed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('previous_status', sa.Text(), nullable=True),
    sa.Column('new_status', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_actions')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_severity', table_name='alerts')
    op.drop_index('ix_alerts_organization_id', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_risk_scores_risk_level', table_name='risk_scores')
    op.drop_index('ix_risk_scores_call_id', table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index('ix_voice_analyses_call_id', table_name='voice_analyses')
    op.drop_index('ix_voice_analyses_audio_segment_id', table_name='voice_analyses')
    op.drop_table('voice_analyses')
    op.drop_index('ix_audio_segments_call_id_sequence', table_name='audio_segments')
    op.drop_index('ix_audio_segments_call_id', table_name='audio_segments')
    op.drop_table('audio_segments')
    op.drop_index('ix_calls_status', table_name='calls')
    op.drop_index('ix_calls_organization_id', table_name='calls')
    op.drop_index('ix_calls_initiated_by_user_id', table_name='calls')
    op.drop_index('ix_calls_created_at', table_name='calls')
    op.drop_table('calls')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_organization_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_organization_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_organizations_slug', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
