// oxlint-disable react(set-state-in-effect), react-hooks(exhaustive-deps)
import { useEffect, useState } from "react";
import { getAccessToken } from "../api/auth";
import { getDashboardOverview, type DashboardOverview } from "../api/dashboard";
import { AnalysisIntakeCard } from "../components/AnalysisIntakeCard";
import "./ProductPages.css";

type Mode = "overview" | "analysis" | "audio" | "alerts" | "reports" | "organization" | "settings";
const I = { shield:"M12 3 20 6v6c0 5-3.5 8.5-8 10-4.5-1.5-8-5-8-10V6l8-3Z", wave:"M3 12h4l2-6 4 12 2-6h6", alert:"M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4", risk:"M12 3 3.5 19h17L12 3Zm0 5v5m0 3v.01", check:"m5 12 4 4L19 6" };
function Icon({d}:{d:string}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={d}/></svg>}
function Count({value}:{value:number}){const[n,setN]=useState(0);useEffect(()=>{let f=0;const s=performance.now();const tick=(t:number)=>{const p=Math.min(1,(t-s)/650);setN(value*(1-Math.pow(1-p,3)));if(p<1)f=requestAnimationFrame(tick)};f=requestAnimationFrame(tick);return()=>cancelAnimationFrame(f)},[value]);return <>{n.toFixed(Number.isInteger(value)?0:1)}</>}
const titles:Record<Mode,[string,string,string]>={overview:["Security overview","Voice security at a glance","Detection, risk and response intelligence for your organization."],analysis:["Analysis","Detection workspace","Review detector outputs, confidence and risk context."],audio:["Audio intake","Analyze a voice recording","Submit an audio sample to the protected analysis pipeline."],alerts:["Alerts","Response center","Review security alerts and move them through the response lifecycle."],reports:["Reports","Security reporting","A clear operational snapshot for your organization."],organization:["Organization","Workspace members","Manage the security workspace and operating posture."],settings:["Settings","Security configuration","Review application, model and policy configuration."]};
function Heading({mode,refresh,onRefresh}:{mode:Mode;refresh:boolean;onRefresh:()=>void}){const t=titles[mode];return <div className="page-heading"><div><span className="eyebrow">{t[0]}</span><h1>{t[1]}</h1><p>{t[2]}</p></div>{mode==="overview"&&<button className={`outline-btn ${refresh?"spinning":""}`} onClick={onRefresh}>↻ Refresh</button>}</div>}
function Metric({label,value,caption,colour,d}:{label:string;value:number;caption:string;colour:string;d:string}){return <article className={`metric ${colour}`}><div className="metric-icon"><Icon d={d}/></div><small>{label}</small><strong><Count value={value}/></strong><span>{caption}</span></article>}
function Feed({title,rows}:{title:string;rows:{id:string;title:string;meta:string;value:string;tone:string}[]}){return <article className="panel"><div className="panel-head"><div><span className="eyebrow">Security feed</span><h2>{title}</h2></div></div><div className="feed">{rows.slice(0,7).map(r=><div className="feed-row" key={r.id}><i className={`severity ${r.tone}`}/><div><b>{r.title}</b><small>{r.meta}</small></div><strong>{r.value}</strong></div>)}</div></article>}
function Overview({data}:{data:DashboardOverview}){const max=Math.max(1,...data.trend.map(x=>x.calls));const points=data.trend.map((x,i)=>`${20+i*740/Math.max(1,data.trend.length-1)},${198-x.calls/max*160}`).join(" ");return <><section className="metric-grid"><Metric label="Analysis sessions" value={Number(data.metrics.calls?.value??0)} caption={data.metrics.calls?.caption??"Current period"} colour="blue" d={I.wave}/><Metric label="Detector runs" value={Number(data.metrics.analyses?.value??0)} caption={data.metrics.analyses?.caption??"Completed"} colour="violet" d={I.shield}/><Metric label="Average risk" value={Number(data.metrics.average_risk?.value??0)} caption={data.metrics.average_risk?.caption??"Deterministic"} colour="amber" d={I.risk}/><Metric label="Active alerts" value={Number(data.metrics.active_alerts?.value??0)} caption={data.metrics.active_alerts?.caption??"Response queue"} colour="rose" d={I.alert}/></section><section className="hero-card"><div><span className="status"><i/> Protection active</span><h2>Detection pipeline online.</h2><p>{data.organization_name} is protected by the AASIST detector and deterministic risk, prevention and alert policies.</p><div className="pipeline"><b>Audio</b><i>→</i><b>Detect</b><i>→</i><b>Risk</b><i>→</i><b>Policy</b><i>→</i><b className="current">Alert</b></div></div><div className="hero-shield"><Icon d={I.shield}/></div></section><section className="content-grid"><article className="panel large"><div className="panel-head"><div><span className="eyebrow">Last 7 days</span><h2>Security activity</h2></div></div><div className="activity-chart"><svg viewBox="0 0 800 225">{[35,88,143,198].map(y=><line key={y} x1="20" x2="780" y1={y} y2={y} stroke="#edf1f6"/>)}<polyline points={points} className="line blue"/></svg><div className="chart-days">{data.trend.map(x=><span key={x.day}>{new Date(`${x.day}T00:00:00`).toLocaleDateString(undefined,{weekday:"short"})}</span>)}</div></div></article><article className="panel"><div className="panel-head"><div><span className="eyebrow">Risk posture</span><h2>Distribution</h2></div></div><div className="risk-stack">{data.risk_distribution.map(r=><div className="risk-item" key={r.level}><div><b>{r.level}</b><span>{r.count}</span></div><div className="bar"><i className={`risk-${r.level.toLowerCase()}`} style={{width:`${r.percentage}%`}}/></div></div>)}</div></article></section><section className="content-grid"><Feed title="Recent alerts" rows={data.recent_alerts.map(a=>({id:a.id,title:a.title,meta:`${a.status.replace("_"," ")} · ${a.severity}`,value:a.risk_score?.toFixed(1)??"—",tone:a.severity.toLowerCase()}))}/><Feed title="Latest analyses" rows={data.recent_analyses.map(a=>({id:a.id,title:a.risk_level??a.detection_status,meta:a.model_version??a.model_name,value:a.risk_score?.toFixed(1)??"—",tone:(a.risk_level??"safe").toLowerCase()}))}/></section><AnalysisIntakeCard/></>}
function Generic({mode,data}:{mode:Mode;data:DashboardOverview|null}){if(mode==="audio")return <><section className="workspace-card"><div className="workspace-icon"><Icon d={I.wave}/></div><div><span className="eyebrow">Protected upload</span><h2>Start a voice analysis</h2><p>Upload a supported recording and send it through processing and detection.</p></div></section><AnalysisIntakeCard/></>;if(mode==="analysis")return <section className="single-panel"><div className="workspace-icon"><Icon d={I.wave}/></div><h2>Detector workspace</h2><p>Review recent AASIST outputs and their deterministic risk context.</p><Feed title="Recent detector activity" rows={(data?.recent_analyses??[]).map(a=>({id:a.id,title:a.risk_level??a.detection_status,meta:`${a.model_name} · ${a.detection_status}`,value:a.risk_score?.toFixed(1)??"—",tone:(a.risk_level??"safe").toLowerCase()}))}/></section>;if(mode==="alerts")return <section className="single-panel"><div className="big-number">{data?.active_alert_count??0}</div><h2>Active alerts</h2><p>Open, acknowledged and investigating alerts for this organization.</p><div className="alert-summary"><span><b>{data?.critical_alert_count??0}</b> Critical</span><span><b>{data?.blocked_action_count??0}</b> Blocked actions</span></div><Feed title="Current response queue" rows={(data?.recent_alerts??[]).map(a=>({id:a.id,title:a.title,meta:`${a.status.replace("_"," ")} · ${a.severity}`,value:a.risk_score?.toFixed(1)??"—",tone:a.severity.toLowerCase()}))}/></section>;if(mode==="reports")return <section className="report-grid">{[["Detection coverage",data?.metrics.analyses?.value??0],["Average risk",data?.metrics.average_risk?.value??0],["Active response",data?.active_alert_count??0],["Blocked outcomes",data?.blocked_action_count??0]].map(([x,v])=><article className="report-card" key={x}><span className="eyebrow">{x}</span><strong>{Number(v).toFixed(x==="Average risk"?1:0)}</strong><p>Current organization period</p></article>)}</section>;if(mode==="organization")return <section className="settings-card"><div className="workspace-icon"><Icon d={I.shield}/></div><span className="eyebrow">Organization</span><h2>{data?.organization_name??"Your organization"}</h2><p>Tenant-scoped security workspace with isolated detection and response data.</p><div className="setting-row"><b>Detection engine</b><span>AASIST · balanced-v1 · Online</span></div><div className="setting-row"><b>Risk policy</b><span>Version 1.0 · Active</span></div></section>;return <section className="settings-card"><div className="workspace-icon"><Icon d={I.shield}/></div><span className="eyebrow">Security configuration</span><h2>Policy stack</h2>{[["Detector threshold","0.5977 · Frozen"],["Risk policy","Version 1.0"],["Prevention policy","Version 1.0"],["Alert policy","Version 1.0"]].map(([a,b])=><div className="setting-row" key={a}><b>{a}</b><span>{b}</span></div>)}</section>}
export function ProductDashboardPage({mode}:{mode:Mode}){
  // API loading intentionally updates local state from an external data source.
  const[data,setData]=useState<DashboardOverview|null>(null);const[refresh,setRefresh]=useState(false);const load=async()=>{const t=getAccessToken();if(!t)return;setRefresh(true);try{setData(await getDashboardOverview(t))}finally{setRefresh(false)}};useEffect(()=>{void load()},[mode]);return <main className="product-page"><Heading mode={mode} refresh={refresh} onRefresh={load}/>{mode==="overview"&&data?<Overview data={data}/>:mode==="overview"?<div className="loading-panel">Loading security overview…</div>:<Generic mode={mode} data={data}/>}</main>}
