import axios from "axios";
import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { AnalysisIntakeCard } from "../components/AnalysisIntakeCard";
import { getAccessToken } from "../api/auth";
import { getDashboardOverview, type DashboardOverview } from "../api/dashboard";
import "./SecurityWorkspace.css";

const API_BASE = import.meta.env.VITE_API_BASE_URL ?? "/api/v1";

const iconPaths = {
  shield: "M12 3 20 6v6c0 5-3.5 8.5-8 10-4.5-1.5-8-5-8-10V6l8-3Z",
  wave: "M3 12h4l2-6 4 12 2-6h6",
  alert: "M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4",
  chart: "M4 19V5m0 14h16M8 16l3-4 3 2 5-7",
  lock: "M7 11V8a5 5 0 0 1 10 0v3m-11 0h12v9H6z",
  arrow: "M5 12h14m-6-6 6 6-6 6",
  check: "m5 12 4 4L19 6",
  clock: "M12 7v5l3 2M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0",
  search: "m20 20-4.5-4.5M10.5 17a6.5 6.5 0 1 0 0-13 6.5 6.5 0 0 0 0 13Z",
};
function Icon({ name }: { name: keyof typeof iconPaths }) { return <svg className="sw-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={iconPaths[name]} /></svg>; }

function useOverview() {
  const [data, setData] = useState<DashboardOverview | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = async () => {
    const token = getAccessToken();
    if (!token) { setError("Session expired. Please sign in again."); setLoading(false); return; }
    setLoading(true); setError("");
    try { setData(await getDashboardOverview(token)); } catch (e) { setError(axios.isAxiosError(e) ? String(e.response?.data?.detail ?? "Unable to load security data") : "Unable to load security data"); } finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, []);
  return { data, loading, error, reload: load };
}

function PageHeader({ eyebrow, title, copy, action }: { eyebrow: string; title: string; copy: string; action?: React.ReactNode }) {
  return <header className="sw-header"><div><span className="sw-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{action}</header>;
}
function Stat({ label, value, detail, tone = "blue", icon }: { label: string; value: string | number; detail: string; tone?: string; icon: keyof typeof iconPaths }) {
  return <article className={`sw-stat ${tone}`}><div className="sw-stat-top"><span className="sw-stat-icon"><Icon name={icon} /></span><span className="sw-stat-label">{label}</span></div><strong>{value}</strong><small>{detail}</small></article>;
}
function RiskBadge({ level }: { level: string | null | undefined }) { const value = (level ?? "SAFE").toUpperCase(); return <span className={`risk-badge ${value.toLowerCase()}`}>{value}</span>; }
function SeverityDot({ severity }: { severity: string }) { return <span className={`severity-dot ${severity.toLowerCase()}`} />; }
function Empty({ title, copy, action }: { title: string; copy: string; action?: React.ReactNode }) { return <div className="sw-empty"><span><Icon name="shield" /></span><h3>{title}</h3><p>{copy}</p>{action}</div>; }
function Loading({ text = "Loading security intelligence…" }: { text?: string }) { return <div className="sw-loading"><i /><span>{text}</span></div>; }

export function SecurityOverviewPage() {
  const { data, loading, error, reload } = useOverview();
  if (loading) return <main className="sw-page"><PageHeader eyebrow="Security console" title="Overview" copy="Real-time visibility across detection, risk and response." /><Loading /></main>;
  if (error || !data) return <main className="sw-page"><PageHeader eyebrow="Security console" title="Overview" copy="Real-time visibility across detection, risk and response." /><div className="sw-error"><h3>Security data unavailable</h3><p>{error || "No overview data is available."}</p><button onClick={() => void reload()}>Retry</button></div></main>;
  const critical = data.risk_distribution.find(x => x.level === "CRITICAL")?.count ?? 0;
  const high = data.risk_distribution.find(x => x.level === "HIGH")?.count ?? 0;
  const max = Math.max(1, ...data.trend.map(x => x.calls));
  const points = data.trend.map((x, i) => `${30 + i * 740 / Math.max(1, data.trend.length - 1)},${185 - x.calls / max * 145}`).join(" ");
  return <main className="sw-page">
    <PageHeader eyebrow="Security console" title={`Good to see you, ${data.organization_name}.`} copy="Your voice-security posture, distilled into one operational view." action={<button className="sw-ghost" onClick={() => void reload()}><Icon name="clock" /> Refresh</button>} />
    <section className="sw-stat-grid"><Stat label="Analysis sessions" value={data.metrics.calls?.value ?? 0} detail={data.metrics.calls?.caption ?? "Current period"} icon="wave" /><Stat label="Detector runs" value={data.metrics.analyses?.value ?? 0} detail={data.metrics.analyses?.caption ?? "Completed"} tone="violet" icon="shield" /><Stat label="Average risk" value={Number(data.metrics.average_risk?.value ?? 0).toFixed(1)} detail="Across analyzed recordings" tone="amber" icon="chart" /><Stat label="Active alerts" value={data.active_alert_count} detail={`${critical} critical · ${high} high`} tone="rose" icon="alert" /></section>
    <section className="sw-command-hero"><div className="hero-copy"><span className="live-pill"><i /> Detection engine online</span><h2>Stop synthetic voices before they become incidents.</h2><p>Every recording can be processed, classified, scored and routed through deterministic response controls.</p><div className="hero-flow"><span>INTAKE</span><b>→</b><span>DETECT</span><b>→</b><span>RISK</span><b>→</b><span>POLICY</span><b>→</b><span className="active">ALERT</span></div></div><div className="hero-orb"><div><Icon name="shield" /></div><i /><i /><i /></div></section>
    <section className="sw-two-col"><article className="sw-panel chart-panel"><div className="sw-panel-head"><div><span className="sw-eyebrow">Last 7 days</span><h2>Security activity</h2></div><span className="chart-caption">Sessions</span></div><div className="sw-chart"><svg viewBox="0 0 800 220" preserveAspectRatio="none"><defs><linearGradient id="activityFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopOpacity=".22" /><stop offset="1" stopOpacity="0" /></linearGradient></defs>{[35,85,135,185].map(y => <line key={y} x1="30" x2="770" y1={y} y2={y} />)}<polyline points={`${points} 770,185 30,185`} className="area" /><polyline points={points} className="chart-line" /></svg><div className="chart-axis">{data.trend.map(x => <span key={x.day}>{new Date(`${x.day}T00:00:00`).toLocaleDateString(undefined, { weekday: "short" })}</span>)}</div></div></article><article className="sw-panel"><div className="sw-panel-head"><div><span className="sw-eyebrow">Risk posture</span><h2>Risk distribution</h2></div></div><div className="risk-list">{data.risk_distribution.map(item => <div className="risk-line" key={item.level}><div><RiskBadge level={item.level} /><strong>{item.count}</strong></div><div className="risk-track"><i className={`fill-${item.level.toLowerCase()}`} style={{ width: `${item.percentage}%` }} /></div><small>{item.percentage.toFixed(0)}%</small></div>)}</div></article></section>
    <section className="sw-two-col"><article className="sw-panel"><div className="sw-panel-head"><div><span className="sw-eyebrow">Response queue</span><h2>Recent alerts</h2></div><Link to="/dashboard/alerts" className="sw-link">View all <Icon name="arrow" /></Link></div>{data.recent_alerts.length ? <div className="sw-list">{data.recent_alerts.slice(0, 5).map(a => <Link to={`/dashboard/alerts/${a.id}`} className="sw-list-row" key={a.id}><SeverityDot severity={a.severity} /><div><strong>{a.title}</strong><small>{a.status.replaceAll("_", " ")} · {new Date(a.created_at).toLocaleString()}</small></div><RiskBadge level={a.severity} /><b>{a.risk_score?.toFixed(1) ?? "—"}</b></Link>)}</div> : <Empty title="No alerts" copy="The response queue is clear." />}</article><article className="sw-panel"><div className="sw-panel-head"><div><span className="sw-eyebrow">Detection feed</span><h2>Latest analyses</h2></div><Link to="/dashboard/analysis" className="sw-link">Explore <Icon name="arrow" /></Link></div>{data.recent_analyses.length ? <div className="sw-list">{data.recent_analyses.slice(0, 5).map(a => <Link to={`/dashboard/analysis/${a.id}`} className="sw-list-row" key={a.id}><span className={`verdict-mark ${(a.detection_status ?? "").toLowerCase() === "SPOOF" ? "bad" : "good"}`}><Icon name="wave" /></span><div><strong>{a.detection_status}</strong><small>{a.model_version ?? a.model_name} · {((a.confidence ?? 0) * 100).toFixed(0)}% confidence</small></div><RiskBadge level={a.risk_level} /><b>{a.risk_score?.toFixed(1) ?? "—"}</b></Link>)}</div> : <Empty title="No analyses yet" copy="Run your first protected voice analysis." action={<Link className="sw-primary" to="/dashboard/audio">Analyze recording</Link>} />}</article></section>
  </main>;
}

export function AnalysisPage() {
  const { data, loading, error } = useOverview();
  const [query, setQuery] = useState("");
  const rows = useMemo(() => (data?.recent_analyses ?? []).filter(x => `${x.detection_status} ${x.model_name} ${x.model_version ?? ""} ${x.risk_level ?? ""}`.toLowerCase().includes(query.toLowerCase())), [data, query]);
  return <main className="sw-page"><PageHeader eyebrow="Detection workspace" title="Voice analyses" copy="Review detector verdicts, confidence and downstream risk context." action={<Link className="sw-primary" to="/dashboard/audio"><Icon name="wave" /> New analysis</Link>} /><div className="sw-toolbar"><div className="sw-search"><Icon name="search" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search analyses…" /></div><span>{rows.length} visible</span></div>{loading ? <Loading /> : error ? <div className="sw-error"><h3>Could not load analyses</h3><p>{error}</p></div> : rows.length ? <div className="sw-table-wrap"><table className="sw-table"><thead><tr><th>Verdict</th><th>Model</th><th>Confidence</th><th>Risk</th><th>Analyzed</th><th /></tr></thead><tbody>{rows.map(a => <tr key={a.id}><td><span className={`table-verdict ${(a.detection_status ?? "").toLowerCase()}`}>{a.detection_status}</span></td><td><strong>{a.model_version ?? a.model_name}</strong><small>{a.model_name}</small></td><td>{((a.confidence ?? 0) * 100).toFixed(1)}%</td><td><RiskBadge level={a.risk_level} /><b>{a.risk_score?.toFixed(1) ?? "—"}</b></td><td>{new Date(a.analyzed_at).toLocaleString()}</td><td><Link className="row-action" to={`/dashboard/analysis/${a.id}`}>Open <Icon name="arrow" /></Link></td></tr>)}</tbody></table></div> : <Empty title="No matching analyses" copy="Try another search or run a new analysis." />}</main>;
}

export function AnalysisDetailPage() {
  const { analysisId } = useParams();
  const navigate = useNavigate();
  const { data, loading, error } = useOverview();
  const item = data?.recent_analyses.find(x => x.id === analysisId);
  if (loading) return <main className="sw-page"><Loading /></main>;
  if (error || !item) return <main className="sw-page"><PageHeader eyebrow="Analysis" title="Analysis not found" copy={error || "This analysis is not available in the current workspace."} /><button className="sw-ghost" onClick={() => navigate("/dashboard/analysis")}>Back to analyses</button></main>;
  const spoof = item.detection_status.toUpperCase() === "SPOOF";
  return <main className="sw-page"><button className="back-link" onClick={() => navigate("/dashboard/analysis")}>← All analyses</button><PageHeader eyebrow="Protected analysis" title={spoof ? "Synthetic voice detected" : "Authentic voice detected"} copy={`Analysis ${item.id}`} /><section className={`analysis-detail-hero ${spoof ? "danger" : "safe"}`}><div className="detail-verdict"><span className="detail-icon"><Icon name={spoof ? "alert" : "check"} /></span><div><span className="sw-eyebrow">Detector verdict</span><h2>{item.detection_status}</h2><p>{spoof ? "The detector identified synthetic voice characteristics." : "The detector classified the recording as authentic."}</p></div></div><div className="confidence-ring"><strong>{((item.confidence ?? 0) * 100).toFixed(0)}%</strong><small>confidence</small></div></section><section className="sw-detail-grid"><article className="sw-panel"><span className="sw-eyebrow">Detector intelligence</span><h2>Model output</h2><div className="prob-row"><span>Synthetic probability</span><b>{((item.synthetic_probability ?? 0) * 100).toFixed(1)}%</b></div><div className="prob-track"><i style={{ width: `${(item.synthetic_probability ?? 0) * 100}%` }} /></div><div className="prob-row"><span>Authentic probability</span><b>{((item.authentic_probability ?? 0) * 100).toFixed(1)}%</b></div><div className="prob-track neutral"><i style={{ width: `${(item.authentic_probability ?? 0) * 100}%` }} /></div><div className="detail-meta"><span>Model<strong>{item.model_version ?? item.model_name}</strong></span><span>Inference<strong>Completed</strong></span></div></article><article className="sw-panel"><span className="sw-eyebrow">Risk intelligence</span><h2><RiskBadge level={item.risk_level} /> <span className="inline-score">{item.risk_score?.toFixed(1) ?? "—"}</span></h2><p className="muted">Risk is calculated from detector output and confidence using the active deterministic policy.</p><div className="risk-meter"><i style={{ width: `${Math.min(100, item.risk_score ?? 0)}%` }} /></div><Link className="sw-primary full" to="/dashboard/alerts">Open response center <Icon name="arrow" /></Link></article></section></main>;
}

async function getAlerts() { const token = getAccessToken(); if (!token) throw new Error("Session expired"); const r = await axios.get(`${API_BASE}/alerts`, { headers: { Authorization: `Bearer ${token}` } }); return r.data.items as AlertRecord[]; }
async function getAlert(id: string) { const token = getAccessToken(); if (!token) throw new Error("Session expired"); const r = await axios.get(`${API_BASE}/alerts/${id}`, { headers: { Authorization: `Bearer ${token}` } }); return r.data as AlertRecord; }
async function getAlertActions(id: string) { const token = getAccessToken(); if (!token) throw new Error("Session expired"); const r = await axios.get(`${API_BASE}/alerts/${id}/actions`, { headers: { Authorization: `Bearer ${token}` } }); return r.data.items as AlertAction[]; }
async function transitionAlert(id: string, status: string, notes?: string) { const token = getAccessToken(); if (!token) throw new Error("Session expired"); const r = await axios.post(`${API_BASE}/alerts/${id}/transition`, { status, notes }, { headers: { Authorization: `Bearer ${token}` } }); return r.data as AlertRecord; }
type AlertRecord = { id: string; organization_id: string; call_id: string | null; risk_score_id: string | null; alert_type: string; severity: string; status: string; title: string; description: string | null; resolved_at: string | null; resolved_by_user_id: string | null; created_at: string };
type AlertAction = { id: string; alert_id: string; performed_by_user_id: string | null; action_type: string; previous_status: string | null; new_status: string | null; notes: string | null; created_at: string };

export function AlertsPage() {
  const [alerts, setAlerts] = useState<AlertRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [filter, setFilter] = useState("ALL");
  const load = async () => { setLoading(true); try { setAlerts(await getAlerts()); } catch (e) { setError(axios.isAxiosError(e) ? String(e.response?.data?.detail ?? "Unable to load alerts") : String(e)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const filtered = alerts.filter(a => filter === "ALL" || a.severity === filter || a.status === filter);
  return <main className="sw-page"><PageHeader eyebrow="Response center" title="Security alerts" copy="Investigate, acknowledge and resolve detected voice-security incidents." action={<button className="sw-ghost" onClick={() => void load()}><Icon name="clock" /> Refresh</button>} /><div className="alert-overview"><Stat label="Open" value={alerts.filter(x => x.status === "OPEN").length} detail="Needs triage" icon="alert" tone="rose" /><Stat label="Investigating" value={alerts.filter(x => x.status === "INVESTIGATING").length} detail="Under review" icon="search" tone="amber" /><Stat label="Critical" value={alerts.filter(x => x.severity === "CRITICAL").length} detail="Immediate attention" icon="shield" tone="violet" /></div><div className="filter-pills">{["ALL", "CRITICAL", "HIGH", "MEDIUM", "OPEN", "INVESTIGATING"].map(x => <button key={x} className={filter === x ? "selected" : ""} onClick={() => setFilter(x)}>{x}</button>)}</div>{loading ? <Loading /> : error ? <div className="sw-error"><h3>Alert service unavailable</h3><p>{error}</p><button onClick={() => void load()}>Retry</button></div> : filtered.length ? <div className="alert-grid">{filtered.map(a => <Link to={`/dashboard/alerts/${a.id}`} className={`alert-card ${a.severity.toLowerCase()}`} key={a.id}><div className="alert-card-top"><SeverityDot severity={a.severity} /><RiskBadge level={a.severity} /><span>{a.status.replaceAll("_", " ")}</span></div><h3>{a.title}</h3><p>{a.description || "Security alert generated from a protected analysis."}</p><div><strong>{a.risk_score?.toFixed(1) ?? "—"}</strong><small>risk score</small><time>{new Date(a.created_at).toLocaleString()}</time></div></Link>)}</div> : <Empty title="Response queue clear" copy="No alerts match the selected filters." />}</main>;
}

export function AlertDetailPage() {
  const { alertId } = useParams(); const navigate = useNavigate(); const [alert, setAlert] = useState<AlertRecord | null>(null); const [actions, setActions] = useState<AlertAction[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = async () => { if (!alertId) return; setLoading(true); try { const [a, h] = await Promise.all([getAlert(alertId), getAlertActions(alertId)]); setAlert(a); setActions(h); } catch (e) { setError(axios.isAxiosError(e) ? String(e.response?.data?.detail ?? "Unable to load alert") : String(e)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [alertId]);
  const act = async (status: string) => { if (!alertId) return; setBusy(true); setError(""); try { await transitionAlert(alertId, status); await load(); } catch (e) { setError(axios.isAxiosError(e) ? String(e.response?.data?.detail ?? "Status transition failed") : String(e)); } finally { setBusy(false); } };
  if (loading) return <main className="sw-page"><Loading /></main>;
  if (error && !alert) return <main className="sw-page"><PageHeader eyebrow="Alert" title="Alert unavailable" copy={error} /><button className="sw-ghost" onClick={() => navigate("/dashboard/alerts")}>Back to alerts</button></main>;
  if (!alert) return null;
  const terminal = ["RESOLVED", "DISMISSED"].includes(alert.status);
  return <main className="sw-page"><button className="back-link" onClick={() => navigate("/dashboard/alerts")}>← Response center</button><PageHeader eyebrow="Incident investigation" title={alert.title} copy={`Alert ${alert.id}`} action={<RiskBadge level={alert.severity} />} /><section className={`incident-banner ${alert.severity.toLowerCase()}`}><div><SeverityDot severity={alert.severity} /><div><span>{alert.severity} severity · {alert.status.replaceAll("_", " ")}</span><h2>{alert.description || "A protected analysis triggered a security alert."}</h2></div></div><strong>{alert.created_at && new Date(alert.created_at).toLocaleString()}</strong></section><section className="incident-grid"><article className="sw-panel"><span className="sw-eyebrow">Response controls</span><h2>Manage incident</h2><p className="muted">Every transition is persisted to the alert action history.</p><div className="incident-actions">{alert.status === "OPEN" && <button disabled={busy} onClick={() => void act("ACKNOWLEDGED")}>Acknowledge</button>}{["OPEN", "ACKNOWLEDGED"].includes(alert.status) && <button disabled={busy} onClick={() => void act("INVESTIGATING")}>Start investigation</button>}{!terminal && <button disabled={busy} onClick={() => void act("RESOLVED")}>Resolve incident</button>}{!terminal && <button className="danger-action" disabled={busy} onClick={() => void act("DISMISSED")}>Dismiss</button>}</div>{error && <div className="inline-error">{error}</div>}</article><article className="sw-panel"><span className="sw-eyebrow">Evidence links</span><h2>Pipeline context</h2><div className="evidence-row"><span>Risk score ID</span><b>{alert.risk_score_id || "—"}</b></div><div className="evidence-row"><span>Analysis / call ID</span><b>{alert.call_id || "—"}</b></div><div className="evidence-row"><span>Alert type</span><b>{alert.alert_type}</b></div></article></section><article className="sw-panel timeline-panel"><div className="sw-panel-head"><div><span className="sw-eyebrow">Audit trail</span><h2>Alert action history</h2></div></div>{actions.length ? <div className="timeline">{actions.map(x => <div className="timeline-item" key={x.id}><span className="timeline-node"><Icon name={x.action_type === "ALERT_CREATED" ? "shield" : "check"} /></span><div><strong>{x.action_type.replaceAll("_", " ")}</strong><small>{x.previous_status ? `${x.previous_status} → ${x.new_status}` : x.new_status || "Event"} · {new Date(x.created_at).toLocaleString()}</small>{x.notes && <p>{x.notes}</p>}</div></div>)}</div> : <Empty title="No actions recorded" copy="The alert has no visible history entries." />}</article></main>;
}

export function AudioPage() { return <main className="sw-page"><PageHeader eyebrow="Protected intake" title="Analyze a recording" copy="Upload one recording and let the full security pipeline make the decision." /><AnalysisIntakeCard /></main>; }
export function ReportsPage() { const { data, loading } = useOverview(); if (loading || !data) return <main className="sw-page"><PageHeader eyebrow="Security reporting" title="Reports" copy="Operational intelligence for your organization." /><Loading /></main>; return <main className="sw-page"><PageHeader eyebrow="Security reporting" title="Reports" copy="Operational intelligence for your organization." /><section className="report-hero"><div><span className="live-pill"><i /> Reporting ready</span><h2>Security posture snapshot</h2><p>Use the live organization metrics below as the basis for incident reviews and demonstrations.</p></div><Link className="sw-primary" to="/dashboard/audio">Run another analysis <Icon name="arrow" /></Link></section><section className="report-grid"><Stat label="Sessions" value={data.metrics.calls?.value ?? 0} detail="Current period" icon="wave" /><Stat label="Detector runs" value={data.metrics.analyses?.value ?? 0} detail="Completed analyses" icon="shield" tone="violet" /><Stat label="Average risk" value={Number(data.metrics.average_risk?.value ?? 0).toFixed(1)} detail="Organization average" icon="chart" tone="amber" /><Stat label="Blocked outcomes" value={data.blocked_action_count} detail="Prevention decisions" icon="lock" tone="rose" /></section><article className="sw-panel"><span className="sw-eyebrow">Policy stack</span><h2>Active controls</h2><div className="policy-grid"><div><b>Detector</b><span>AASIST family · balanced-v1</span></div><div><b>Threshold</b><span>0.5977 · frozen from DEV analysis</span></div><div><b>Risk policy</b><span>Version 1.0</span></div><div><b>Prevention</b><span>Version 1.0</span></div><div><b>Alerting</b><span>Version 1.0</span></div><div><b>Tenant model</b><span>Organization-scoped data access</span></div></div></article></main>; }
export function OrganizationPage() { const { data, loading } = useOverview(); return <main className="sw-page"><PageHeader eyebrow="Administration" title="Organization" copy="Workspace identity and security posture." />{loading ? <Loading /> : <section className="org-profile"><div className="org-crest"><Icon name="shield" /></div><span className="sw-eyebrow">Protected workspace</span><h2>{data?.organization_name ?? "Organization"}</h2><p>Tenant-scoped detection, risk, prevention and alert data.</p><div className="org-facts"><span><b>Detection engine</b>AASIST · balanced-v1</span><span><b>Policy version</b>1.0</span><span><b>Response model</b>Deterministic</span><span><b>Data boundary</b>Organization isolated</span></div></section>}</main>; }
export function SettingsPage() { return <main className="sw-page"><PageHeader eyebrow="Administration" title="Security settings" copy="Review the controls currently governing the detection pipeline." /><section className="settings-grid"><article className="sw-panel"><span className="sw-eyebrow">AI detection</span><h2>Detector configuration</h2>{[["Model","AASIST-family"],["Version","balanced-v1"],["Sample rate","16,000 Hz"],["Decision threshold","0.5977"],["Confidence output","Enabled"]].map(([a,b]) => <div className="setting-line" key={a}><b>{a}</b><span>{b}</span></div>)}</article><article className="sw-panel"><span className="sw-eyebrow">Response controls</span><h2>Policy configuration</h2>{[["Risk policy","Version 1.0"],["SAFE / LOW","ALLOW"],["MEDIUM","MONITOR"],["HIGH","REQUIRE REVIEW"],["CRITICAL","BLOCK"],["Alerting","MEDIUM / HIGH / CRITICAL"]].map(([a,b]) => <div className="setting-line" key={a}><b>{a}</b><span>{b}</span></div>)}</article></section></main>; }
